# Generated by Django 6.0.3 on 2026-03-19 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fthg', models.SmallIntegerField(max_length=2, verbose_name='uy toliq vaqt gol ')),
                ('ftag', models.SmallIntegerField(max_length=2, verbose_name='mehmon toliq vaqt gol ')),
                ('ftr', models.SmallIntegerField(choices=[(1, 'h'), (2, 'd'), (3, 'a')])),
                ('hthg', models.SmallIntegerField(max_length=2, verbose_name='uy yarim vaqt gol ')),
                ('htag', models.SmallIntegerField(max_length=2, verbose_name='mehmon yarim vaqt gol ')),
                ('hs', models.SmallIntegerField(max_length=3, verbose_name='uy zarbalar soni ')),
                ('a_s', models.SmallIntegerField(max_length=3, verbose_name='mehmon zarbalar soni ')),
                ('hst', models.SmallIntegerField(max_length=2, verbose_name='uy aniq zarbalar soni ')),
                ('ast', models.SmallIntegerField(max_length=2, verbose_name='mehmon aniq zarbalar soni ')),
                ('hf', models.SmallIntegerField(max_length=2, verbose_name='uy follar ')),
                ('af', models.SmallIntegerField(max_length=2, verbose_name='mehmon follar ')),
                ('hc', models.SmallIntegerField(max_length=2, verbose_name='uy burchak zarbalar soni ')),
                ('ac', models.SmallIntegerField(max_length=2, verbose_name='mehmon burchak soni ')),
                ('hy', models.SmallIntegerField(max_length=2, verbose_name='uy sariq soni ')),
                ('ay', models.SmallIntegerField(max_length=2, verbose_name='mehmon sariq soni ')),
                ('hr', models.SmallIntegerField(max_length=2, verbose_name='uy qizil soni ')),
                ('ar', models.SmallIntegerField(max_length=2, verbose_name='mehmon qizil soni ')),
                ('div', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match', to='app.division')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referee', to='app.referee')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_team', to='app.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_team', to='app.team')),
            ],
        ),
    ]
