# Generated by Django 6.0.3 on 2026-03-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='a_s',
            field=models.SmallIntegerField(verbose_name='mehmon zarbalar soni '),
        ),
        migrations.AlterField(
            model_name='match',
            name='ac',
            field=models.SmallIntegerField(verbose_name='mehmon burchak soni '),
        ),
        migrations.AlterField(
            model_name='match',
            name='af',
            field=models.SmallIntegerField(verbose_name='mehmon follar '),
        ),
        migrations.AlterField(
            model_name='match',
            name='ar',
            field=models.SmallIntegerField(verbose_name='mehmon qizil soni '),
        ),
        migrations.AlterField(
            model_name='match',
            name='ast',
            field=models.SmallIntegerField(verbose_name='mehmon aniq zarbalar soni '),
        ),
        migrations.AlterField(
            model_name='match',
            name='ay',
            field=models.SmallIntegerField(verbose_name='mehmon sariq soni '),
        ),
        migrations.AlterField(
            model_name='match',
            name='ftag',
            field=models.SmallIntegerField(verbose_name='mehmon toliq vaqt gol '),
        ),
        migrations.AlterField(
            model_name='match',
            name='fthg',
            field=models.SmallIntegerField(verbose_name='uy toliq vaqt gol '),
        ),
        migrations.AlterField(
            model_name='match',
            name='hc',
            field=models.SmallIntegerField(verbose_name='uy burchak zarbalar soni '),
        ),
        migrations.AlterField(
            model_name='match',
            name='hf',
            field=models.SmallIntegerField(verbose_name='uy follar '),
        ),
        migrations.AlterField(
            model_name='match',
            name='hr',
            field=models.SmallIntegerField(verbose_name='uy qizil soni '),
        ),
        migrations.AlterField(
            model_name='match',
            name='hs',
            field=models.SmallIntegerField(verbose_name='uy zarbalar soni '),
        ),
        migrations.AlterField(
            model_name='match',
            name='hst',
            field=models.SmallIntegerField(verbose_name='uy aniq zarbalar soni '),
        ),
        migrations.AlterField(
            model_name='match',
            name='htag',
            field=models.SmallIntegerField(verbose_name='mehmon yarim vaqt gol '),
        ),
        migrations.AlterField(
            model_name='match',
            name='hthg',
            field=models.SmallIntegerField(verbose_name='uy yarim vaqt gol '),
        ),
        migrations.AlterField(
            model_name='match',
            name='hy',
            field=models.SmallIntegerField(verbose_name='uy sariq soni '),
        ),
    ]
