# Generated by Django 6.0.3 on 2026-03-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_match_a_s_alter_match_ac_alter_match_af_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ftr',
            field=models.CharField(choices=[(1, 'h'), (2, 'd'), (3, 'a')]),
        ),
    ]
