# Generated by Django 6.0.3 on 2026-03-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_match_ftr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='referee',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='referee',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='referee',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='a_s',
            field=models.SmallIntegerField(blank=True, db_column='as', null=True, verbose_name='Away shots'),
        ),
        migrations.AlterField(
            model_name='match',
            name='ac',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Away corners'),
        ),
        migrations.AlterField(
            model_name='match',
            name='af',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Away fouls'),
        ),
        migrations.AlterField(
            model_name='match',
            name='ar',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Away red cards'),
        ),
        migrations.AlterField(
            model_name='match',
            name='ast',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Away shots on target'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='app.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='ay',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Away yellow cards'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='ftag',
            field=models.SmallIntegerField(verbose_name='Full-time away goals'),
        ),
        migrations.AlterField(
            model_name='match',
            name='fthg',
            field=models.SmallIntegerField(verbose_name='Full-time home goals'),
        ),
        migrations.AlterField(
            model_name='match',
            name='ftr',
            field=models.CharField(choices=[(1, 'h'), (2, 'd'), (3, 'a')], max_length=1, verbose_name='Full-time result'),
        ),
        migrations.AlterField(
            model_name='match',
            name='hc',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Home corners'),
        ),
        migrations.AlterField(
            model_name='match',
            name='hf',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Home fouls'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='app.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='hr',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Home red cards'),
        ),
        migrations.AlterField(
            model_name='match',
            name='hs',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Home shots'),
        ),
        migrations.AlterField(
            model_name='match',
            name='hst',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Home shots on target'),
        ),
        migrations.AlterField(
            model_name='match',
            name='htag',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Half-time away goals'),
        ),
        migrations.AlterField(
            model_name='match',
            name='hthg',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Half-time home goals'),
        ),
        migrations.AlterField(
            model_name='match',
            name='hy',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Home yellow cards'),
        ),
        migrations.AlterField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='app.referee'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=10)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
            options={
                'ordering': ['-start_year'],
                'unique_together': {('name', 'division')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app.season'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('season', 'home_team', 'away_team', 'date')},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['season'], name='app_match_season__60a48b_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['date'], name='app_match_date_3ffd4a_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['home_team'], name='app_match_home_te_a6238d_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['away_team'], name='app_match_away_te_68d528_idx'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='div',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
    ]
